### ISSUE TITLE
RFC - When no token, all methods should be stubbed

### ISSUE THREAD

**Issue by trisrael** [AltSchool/ember-segmentio#3]
When `window.analytics` has not been loaded cause Javascript errors (Currently the main two contenders are  `identify` and `track`). Without [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to allow for method missing type handling and also because `unknownProperty` unusable due to current interface on segmentio service which does not rely on `get` of methods.

In order to deal with this issue the proposal is to use a slightly different interface than current implementation to allow for these calls to be made without error and to warn of missing analytics object during development.

```
segmentio: Ember.inject.service(),
actions: {
  someThing: function() {
    this.get('segmentio').track('MyItem', {someThing: blah})
    ...
  }
}
```

**Proposed**

```
segmentio: Ember.inject.service(),
actions: {
  someThing: function() {
    this.get('segmentio').send('track', 'MyItem', {someThing: blah})
    ...
  }
}
```

In order to be able to hook in and call `Ember.warn` when not available, and do nothing when `window.analytics` not pulled in.

**Comment by alexgb** [comment]
Doesn't segment already implement this for us? If you include their stub in `head` it implements `track`, `page` etc. It's not until you later call `analytics.load(SEGMENT_KEY)`, if and when you have a key, that it then loads the full library, drains the call queues, and properly implements `track`, `page` and friends.

**Comment by trisrael** [comment]
Yep makes sense - will simply not call the analytics load then in the initializer
